#!.venv/bin/python3
"""Plot waveform CSV files generated by scope-capture.py."""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path

import matplotlib.pyplot as plt


def get_sudo_owner() -> tuple[int, int] | None:
    if os.geteuid() != 0:
        return None
    uid = os.environ.get("SUDO_UID")
    gid = os.environ.get("SUDO_GID")
    if not uid or not gid:
        return None
    try:
        return int(uid), int(gid)
    except ValueError:
        return None


def ensure_path_owner(path: Path) -> None:
    owner = get_sudo_owner()
    if owner is None or not path.exists():
        return
    uid, gid = owner
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        return


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize scope-capture waveform CSV data with matplotlib.",
        add_help=False,
    )
    parser.add_argument("--help", action="help", help="show this help message and exit")
    parser.add_argument("csv_files", nargs="+", help="One or more CSV files from scope-capture.py")
    parser.add_argument(
        "-o",
        dest="output",
        help="Optional output image path (e.g. plot.png).",
    )
    parser.add_argument(
        "--title",
        default="DSO-X Waveforms",
        help="Plot title",
    )
    parser.add_argument(
        "-i",
        "--cap-idx",
        dest="capture_index",
        type=int,
        default=-1,
        help="For duration/long-format CSV, select capture index (default: latest)",
    )
    parser.add_argument(
        "-c",
        "--channel",
        help="Channel/source to plot (default: all). Examples: CHAN1, CHAN1_v, MATH",
    )
    parser.add_argument(
        "--graph",
        action="store_true",
        help="Display interactive graph window",
    )
    if "-h" in sys.argv[1:]:
        parser.error("'-h' is disabled; use --help")
    return parser.parse_args()


def read_wide_csv(reader: csv.DictReader) -> tuple[list[float], dict[str, list[float]]]:
    headers = reader.fieldnames or []
    value_columns = [h for h in headers if h not in ("sample_index", "time_s")]
    if not value_columns:
        raise ValueError("CSV has no waveform columns (expected *_v columns).")

    time_s: list[float] = []
    waveforms: dict[str, list[float]] = {col: [] for col in value_columns}

    for row in reader:
        t_raw = (row.get("time_s") or "").strip()
        if not t_raw:
            continue
        t_val = float(t_raw)
        time_s.append(t_val)
        for col in value_columns:
            v_raw = (row.get(col) or "").strip()
            waveforms[col].append(float(v_raw) if v_raw else float("nan"))
    return time_s, waveforms


def read_long_csv(
    reader: csv.DictReader,
    capture_index: int,
) -> tuple[list[float], dict[str, list[float]]]:
    rows = [row for row in reader]
    available_captures = sorted(
        {int((row.get("capture_index") or "").strip()) for row in rows if (row.get("capture_index") or "").strip()}
    )
    if not available_captures:
        raise ValueError("Long-format CSV has no capture_index values.")

    selected_capture = available_captures[-1] if capture_index < 0 else capture_index
    if selected_capture not in available_captures:
        raise ValueError(
            f"Capture index {selected_capture} not found. Available: {available_captures}"
        )

    by_source: dict[str, list[tuple[int, float, float]]] = {}
    for row in rows:
        ci_raw = (row.get("capture_index") or "").strip()
        if not ci_raw or int(ci_raw) != selected_capture:
            continue
        source = (row.get("source") or "").strip()
        if not source:
            continue
        si_raw = (row.get("sample_index") or "").strip()
        t_raw = (row.get("time_s") or "").strip()
        v_raw = (row.get("voltage_v") or "").strip()
        if not si_raw or not t_raw or not v_raw:
            continue
        by_source.setdefault(source, []).append((int(si_raw), float(t_raw), float(v_raw)))

    if not by_source:
        raise ValueError(f"No samples found for capture_index={selected_capture}.")

    common_time: list[float] = []
    waveforms: dict[str, list[float]] = {}
    first_source = next(iter(by_source))
    first_data = sorted(by_source[first_source], key=lambda x: x[0])
    common_time = [t for _, t, _ in first_data]

    for source, samples in by_source.items():
        ordered = sorted(samples, key=lambda x: x[0])
        waveforms[source] = [v for _, _, v in ordered]

    return common_time, waveforms


def read_waveform_csv(path: Path, capture_index: int) -> tuple[list[float], dict[str, list[float]]]:
    with path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        if "time_s" not in headers:
            raise ValueError("CSV must contain a 'time_s' column.")
        is_long_format = {"capture_index", "source", "voltage_v"}.issubset(set(headers))
        if is_long_format:
            return read_long_csv(reader, capture_index)
        return read_wide_csv(reader)


def main() -> int:
    args = parse_args()
    plt.figure(figsize=(10, 5))
    plotted_any = False
    for file_arg in args.csv_files:
        csv_path = Path(file_arg)
        if not csv_path.exists():
            raise FileNotFoundError(f"CSV not found: {csv_path}")

        time_s, waveforms = read_waveform_csv(csv_path, args.capture_index)
        if args.channel:
            requested = args.channel.strip()
            selected_name = None
            for name in waveforms:
                if name == requested or name.rstrip("_v") == requested:
                    selected_name = name
                    break
            if selected_name is None:
                available = ", ".join(waveforms.keys())
                raise ValueError(f"Channel '{requested}' not found in {csv_path.name}. Available: {available}")
            waveforms = {selected_name: waveforms[selected_name]}

        if not time_s:
            continue
        t0 = min(time_s)
        plot_time = [t - t0 for t in time_s]

        for name, values in waveforms.items():
            label = f"{csv_path.stem}:{name}" if len(args.csv_files) > 1 else name
            plt.plot(plot_time, values, label=label, linewidth=1.0)
            plotted_any = True

    if not plotted_any:
        raise ValueError("No time samples found in provided CSV file(s).")

    plt.title(args.title)
    plt.xlabel("Time from start (s)")
    plt.ylabel("Voltage (V)")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_path, dpi=150)
        ensure_path_owner(out_path)
        ensure_path_owner(out_path.parent)
        print(f"Saved plot: {args.output}")
    if args.graph or not args.output:
        plt.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
