#pragma once

#include <string_view>
#include "datatypes.hpp"

#define PORT_TIMEOUT    -1              // Used when communication on the port times out
#define PORT_MSG        0x02            // Used when the device wants to send a printable message
#define PORT_MSG_END    0x03            // Used when the device wants to stop sending a printable message
#define PORT_TRN_END    0x04            // Used to signal end of transmission
#define PORT_ACK        0x06            // Used for acknowledging data received
#define PORT_NAK        0x15            // Used for acknowledging invalid data or error

class Serial
{
    public:

    enum class Error
    {
        NO_ERROR = 0,
        INVALID_PATH,
        INVALID_CONFIG,
        INVALID_BITRATE,
        READ_ERROR,
        WRITE_ERROR,
        CTRL_ERROR
    };

    enum class Baudrate
    {
        BR9600
    };

    /**
     * Construct a serial bus interface.
     * @param path The path to the serial bus interface device.
     * @param baudrate The baudrate to use for communication.
     * @param timeout_ms The amount of time to wait for communication before assuming a timeout.
     */
    Serial(const char* path, Baudrate baudrate, u32 timeout_ms);

    /**
     * Destructor for the serial interface.
     */
    ~Serial();

    /**
     * Serial device ownership is unique and cannot be copied.
     */
    Serial(const Serial&) = delete;
    Serial& operator=(const Serial&) = delete;

    /**
     * Move ownership of the serial device handle.
     */
    Serial(Serial&& other) noexcept;
    Serial& operator=(Serial&& other) noexcept;

    /**
     * Checks if a device has been successfully opened and configured and is ready for use.
     * @return `true` if the device is ready for use, `false` otherwise.
     */
    bool available(void);

    /**
     * Returns the latest error generated by this device
     * @return The value of the error
     */
    Error getError(void);

    /**
     * Returns the number of bytes available for reading on the serial interface.
     * @return The number of bytes
     */
    u32 dataAvailable(void);

    /**
     * Waits for data to be available on the serial interface.
     * @return `true` if data was received, `false` otherwise.
     */
    [[nodiscard]] bool awaitData(void);

    /**
     * Waits for at least `count` bytes of data to be available on the serial interface.
     * @param count The number of bytes on the interface to await for.
     * @return `true` if at least `count` bytes were received, `false` otherwise.
     */
    [[nodiscard]] bool awaitData(u32 count);

    /**
     * Send a single byte of data over the serial interface.
     * @param data The data to send.
     */
    void writeByte(u8 data);

    /**
     * Writes `count` number of bytes of data to the serial interface from `src`.
     * The caller must ensure that `src` is at least `count` bytes long.
     * @param src The source for the written bytes.
     * @param count The number of bytes to write to the port.
     */
    void writeBytes(const u8* src, u32 count);

    /**
     * Read a single byte of data from the serial interface.
     * @return The data that was transmitted.
     */
    u8 readByte(void);

    /**
     * Reads `count` number of bytes of data from the serial interface and places them in `dest`.
     * The caller must ensure that `dest` is at least `count` bytes long.
     * @param dest The destination for the read bytes.
     * @param count The number of bytes to read from the port.
     * @return The number of bytes read from the port.
     */
    u32 readBytes(u8* dest, u32 count);

    private:
        struct Impl;
        Impl* _handle;
        u32 _timeout_ms;
        u32 _baudrate;
        Error _error;
};
