#!/bin/env python3
"""
Process images for int8 embedded MNIST inference.

Converts PNG/JPG images to the int8 format expected by the Arduino MNIST model.
The model (StandardANN_Int8_Shift) was trained with inputs in [-128, 127],
using the transform: grayscale_pixel - 128 (matching use_int8_range=True).

Usage:
    python process_image.py input.png output.bin
    python process_image.py input.png output.h --header
    python process_image.py input_dir/ output_dir/ --batch
"""

import argparse
import struct
import sys
from pathlib import Path

from PIL import Image

# Model constants (from weights.hpp)
ANN_INPUT_SIZE = 36  # 6x6 image


def load_and_resize_image(image_path: Path) -> list[int]:
    """
    Load an image and convert to 6x6 grayscale pixels (0-255).

    Accepts:
    - Exact 6x6 images
    - Integer multiples of 6x6 (e.g., 60x60) - averaged blocks
    - Any size - resized with bicubic interpolation
    """
    img = Image.open(image_path).convert("L")
    width, height = img.size

    if (width, height) == (6, 6):
        return list(img.getdata())

    # Check if it's an integer multiple of 6
    if width % 6 == 0 and height % 6 == 0 and width == height:
        scale = width // 6
        pixels = []
        for ty in range(6):
            for tx in range(6):
                left = tx * scale
                top = ty * scale
                block = img.crop((left, top, left + scale, top + scale))
                avg = sum(block.getdata()) // (scale * scale)
                pixels.append(avg)
        return pixels

    # Otherwise, resize to 6x6
    img_resized = img.resize((6, 6), Image.Resampling.BICUBIC)
    return list(img_resized.getdata())


def pixels_to_int8(pixels: list[int]) -> list[int]:
    """
    Convert 0-255 grayscale pixels to int8 values for the model.

    The model was trained with input_shift=0 and use_int8_range=True,
    meaning inputs are simply: grayscale_pixel - 128
    This maps [0, 255] to [-128, 127].
    """
    return [max(-128, min(127, pixel - 128)) for pixel in pixels]


def get_label(image_path: Path) -> int | None:
    """Parse label from filename if it matches 'digit_X_Y.png'."""
    import re
    basename = image_path.name
    match = re.match(r'digit_(\d)_.*\.png$', basename)
    if match:
        label = int(match.group(1))
        if 0 <= label <= 9:
            return label
    return None


def write_binary(int8_values: list[int], output_path: Path, label: int | None = None):
    """Write int8 values as raw binary file, optionally with label."""
    with open(output_path, "wb") as f:
        for val in int8_values:
            # Pack as signed byte
            f.write(struct.pack("b", val))
        if label is not None:
            f.write(struct.pack("B", label))


def write_header(int8_values: list[int], output_path: Path, var_name: str = "input_data", label: int | None = None):
    """Write int8 values as C header file, optionally with label."""
    with open(output_path, "w") as f:
        f.write(f"#pragma once\n\n")
        f.write(f"// Generated by process_image.py\n")
        f.write(f"// Input data for int8 MNIST model\n\n")
        f.write(f"#include <stdint.h>\n\n")
        size = len(int8_values) + (1 if label is not None else 0)
        f.write(f"static const int8_t {var_name}[{size}] = {{\n    ")

        for i, val in enumerate(int8_values):
            f.write(f"{val:4d}")
            if i < len(int8_values) - 1:
                f.write(",")
                if (i + 1) % 6 == 0:  # New line every row
                    f.write("\n    ")
                else:
                    f.write(" ")

        if label is not None:
            f.write(f",\n    {label:4d}")

        f.write("\n};\n")


def print_preview(pixels: list[int], int8_values: list[int], label: int | None):
    """Print a visual preview of the image."""
    chars = " .:-=+*#%@"

    print("\nOriginal (0-255):")
    for row in range(6):
        line = ""
        for col in range(6):
            idx = row * 6 + col
            char_idx = min(pixels[idx] * len(chars) // 256, len(chars) - 1)
            line += chars[char_idx] * 2
        print(f"  {line}")

    print("\nQuantized int8 values:")
    for row in range(6):
        vals = int8_values[row * 6 : (row + 1) * 6]
        print(f"  {vals}")
    if label is not None:
        print(f"Label: {label}")


def process_single(input_path: Path, output_path: Path, as_header: bool, preview: bool):
    """Process a single image."""
    pixels = load_and_resize_image(input_path)
    int8_values = pixels_to_int8(pixels)
    label = get_label(input_path)

    if preview:
        print_preview(pixels, int8_values, label)

    if as_header:
        var_name = input_path.stem.replace("-", "_").replace(" ", "_")
        write_header(int8_values, output_path, var_name, label)
    else:
        write_binary(int8_values, output_path, label)

    print(f"Converted: {input_path} -> {output_path}")


def process_batch(input_dir: Path, output_dir: Path, as_header: bool):
    """Process all images in a directory."""
    output_dir.mkdir(parents=True, exist_ok=True)

    extensions = {".png", ".jpg", ".jpeg", ".bmp", ".gif"}
    images = [f for f in input_dir.iterdir() if f.suffix.lower() in extensions]

    if not images:
        print(f"No images found in {input_dir}")
        return

    for img_path in sorted(images):
        ext = ".h" if as_header else ".bin"
        out_path = output_dir / (img_path.stem + ext)
        process_single(img_path, out_path, as_header, preview=False)

    print(f"\nProcessed {len(images)} images")


def main():
    parser = argparse.ArgumentParser(
        description="Process images for int8 embedded MNIST inference"
    )
    parser.add_argument("input", type=Path, help="Input image or directory")
    parser.add_argument("output", type=Path, help="Output file or directory")
    parser.add_argument(
        "--header", "-H", action="store_true", help="Output as C header instead of binary"
    )
    parser.add_argument(
        "--batch", "-b", action="store_true", help="Process entire directory"
    )
    parser.add_argument(
        "--preview", "-p", action="store_true", help="Show ASCII preview of image"
    )

    args = parser.parse_args()

    if args.batch:
        if not args.input.is_dir():
            print(f"Error: {args.input} is not a directory", file=sys.stderr)
            sys.exit(1)
        process_batch(args.input, args.output, args.header)
    else:
        if not args.input.is_file():
            print(f"Error: {args.input} does not exist", file=sys.stderr)
            sys.exit(1)
        process_single(args.input, args.output, args.header, args.preview)


if __name__ == "__main__":
    main()
