/*
 * StandardANN_Int8_Fixed - 8-bit Quantized Weights for Embedded Deployment
 * Generated by gilgamesh snntorch_comparison.py
 *
 * Network: 36 -> 12 -> 10
 * Quantization: 8-bit signed integers (-128 to 127)
 * Format: real_value = int_value * scale
 */

#ifndef STANDARDANN_INT8_FIXED_WEIGHTS_8BIT_H
#define STANDARDANN_INT8_FIXED_WEIGHTS_8BIT_H

#include <stdint.h>

/* Network Configuration */
#define STANDARDANN_INT8_FIXED_INPUT_SIZE  36
#define STANDARDANN_INT8_FIXED_HIDDEN_SIZE 12
#define STANDARDANN_INT8_FIXED_OUTPUT_SIZE 10
#define STANDARDANN_INT8_FIXED_BITS        8

/* Scale Factors (real_value = int_value * scale) */
#define STANDARDANN_INT8_FIXED_FC1_WEIGHT_SCALE_SCALE 0.0000139954f
#define STANDARDANN_INT8_FIXED_FC1_BIAS_SCALE_SCALE 0.0000124099f
#define STANDARDANN_INT8_FIXED_FC1_WEIGHT_SCALE 0.0013118227f
#define STANDARDANN_INT8_FIXED_FC1_BIAS_SCALE 0.0010451439f
#define STANDARDANN_INT8_FIXED_FC2_WEIGHT_SCALE_SCALE 0.0000225795f
#define STANDARDANN_INT8_FIXED_FC2_BIAS_SCALE_SCALE 0.0000348568f
#define STANDARDANN_INT8_FIXED_FC2_WEIGHT_SCALE 0.0022582260f
#define STANDARDANN_INT8_FIXED_FC2_BIAS_SCALE 0.0057942369f

/* fc1_weight_scale: shape=[], total=1 */
static const int8_t StandardANN_Int8_Fixed_fc1_weight_scale[1] = {
     127,
};

/* fc1_bias_scale: shape=[], total=1 */
static const int8_t StandardANN_Int8_Fixed_fc1_bias_scale[1] = {
     127,
};

/* fc1_weight: shape=[12, 36], total=432 */
static const int8_t StandardANN_Int8_Fixed_fc1_weight[432] = {
      97,  105,  -30,  117,  -28,   26,  -62,   75,  112,  -93,  110,   24,   94,   17,   61,  -18,
      98,   19,  -59,   32,  -59,  -15,  -52,   84, -100,  -59,  -36,  -76,   12, -125,  115, -108,
      98,   21,  -41,   79,   20,  103,   14,  -40,   34,  -34,   53,  113,   73,  -56,   73,   23,
      65,  -77, -126,  -49,  -97,  104,   37,   53,   40,   -2,   99,  -90,    8,  -87,   39,  -44,
      39,  -26,  105,  -75,  -76,  -76,  114,   42,  122, -105, -126,  -99,  -85,   51,   45,  106,
     -66,  -87,   67,  -51,   77,  -30,   73,  -99,  -64,   39,   27,  -32,   76,   86,  -92,  -68,
     116,  -43,  -45, -123,  -73,   32,  -17,  -92,    3,  -87, -108,  -70, -111,  -81,  127,   24,
      39, -118,  -83,  -42,   20, -112,  -55,  -76,    0,  -47,   -9,  -86,  -87,  -74,  -43, -100,
     107,  -25,  109,   40, -108,   88,  -35,  -49, -105, -126,   36,  -28,   49, -104,   94,  -93,
     -22,   27,   66,  103,  116, -101,   32,  -55,  -14,  -95,  116,  -93,   68,   45,   41,  -69,
     115,   28,   16, -112,   53,  -19,  -58,  109,   28,  -70,  -64,   -6,   71,  -32,  -72,  -44,
     -95,   45,   98, -120,   30,   66,   23,  -45,   66,   67,   48,  -22,  -34,   14,  -22,  -38,
      81,  109,  -13,  -28,    2,   -8,   31,   36, -115,  -47,  107,   49,   -6,  -77,  -78, -114,
     -41,   43,   81,   59, -112,  -76,  -20,  123,   18,  -33,   53,  -48,  -82,   93,  -58,  -25,
    -126,   85,   96,   46,  -89, -125, -103,   95,   61,  107,   67,   32,   -1,  -97, -109, -119,
      52,  -62,  -26,  -73,  -23,  -89,  -83,   42,  -38,   78,  -41,  -93,  -22,  -62,  -39, -121,
      71,  -88,   64,   58,   91,  -97,   91,  -60,   47,  119,  -18,   -1,  -29, -106,   61, -126,
      79,   95,  120,  -30, -104,   29,   70, -126,  -29,  -76,  -11,  -63,  -52,  -40, -121,  104,
     107,  -20,  -14,  -52, -115, -124,   47,  -70,  -82,  -10,  -42,  -41,    4,  -27,  -44,  -61,
    -103,  107,  -51,   34,  -44,   10,  118,   59, -110,   50,  121,   33,   85,  125,  -19,   26,
     -88,  -26,   94,   65,  -80, -102,  -87, -125,  -98,  -31,   86,   21,  -97, -102,   63,  -95,
     -16,   61,  -59,  -14,  -11,  -30,  -64, -113, -103,  -68,  123,  -61,  -85,   31,   35,   70,
      97,   71, -126,   11,   77,  -12,  -75,  121,  -48,  -72, -115,    6,   56,   28,   25,  -96,
    -119,    2,  116,   73,  -74,  -16,  -94,  -61,   23,   69,  105, -117,   85,  -90,   48,  108,
       2,  116, -108,  -49,   74,  -28,  -26,  -53,   88,   62,   41,  -71, -103,   14,   38,  -59,
     -36,   86,   10,    6,  -31, -115, -119,  -61,  -65,   40,  -37,  -50,  121,   44,   91,  -62,
     -52,   47,  -85,  -83,   -6,  -46,  -95,   75,  102,   21,  -22, -118,  -46,   32,   60,  -16,
};

/* fc1_bias: shape=[12], total=12 */
static const int8_t StandardANN_Int8_Fixed_fc1_bias[12] = {
     -63,   89, -127,  101,  -62,    2,  -32,   19,  -48,  116,   -4,  124,
};

/* fc2_weight_scale: shape=[], total=1 */
static const int8_t StandardANN_Int8_Fixed_fc2_weight_scale[1] = {
     127,
};

/* fc2_bias_scale: shape=[], total=1 */
static const int8_t StandardANN_Int8_Fixed_fc2_bias_scale[1] = {
     127,
};

/* fc2_weight: shape=[10, 12], total=120 */
static const int8_t StandardANN_Int8_Fixed_fc2_weight[120] = {
     123,  -62,  -93,  103,  100,  -98,  -10, -126, -105,   25,   34,   27,  -35,  118,   18,  -75,
      -7,   31,   45,  -90,   48,  -65, -106,  -70,  123,  109,  114,   75,   97,  -17,  -70,   64,
     -66,  -86,  -41,   27,   66,  -50,  -75,   17,  -75,  -83,   67,  -21,  117,  124,   38,   44,
      29,    2,   -9,    2,   48,  119,  -33,  -54,  -31,  -62,   22,   95,  100,   59,  -94,  -69,
     -28,  -24,   11, -117,   40,  -98,  -81, -106,  111, -121,   96,   -4,  -15,   80,  -12,   80,
      92, -111,   49,   24,   27,   19,   35,  -61,  -16,  121,   86,   -5, -120,    6,  -87,  104,
     -78,   -9,  -28,   23,  120,   12,   74,   99,  103,  -44,  -29,   62,  -35,   60,  -28,  -87,
      52,   20,   57,  127,   87,  121,    7, -110,
};

/* fc2_bias: shape=[10], total=10 */
static const int8_t StandardANN_Int8_Fixed_fc2_bias[10] = {
     -47,   63,  -49,   -7,  -69, -127,  -43,  -10,  -52,   11,
};

#endif /* STANDARDANN_INT8_FIXED_WEIGHTS_8BIT_H */