/*
 * StandardANN_Int8_Shift - 8-bit Quantized Weights for Embedded Deployment
 * Generated by gilgamesh snntorch_comparison.py
 *
 * Network: 36 -> 14 -> 10
 * Quantization: 8-bit signed integers (-128 to 127)
 * Format: real_value = int_value * scale
 */

#ifndef STANDARDANN_INT8_SHIFT_WEIGHTS_8BIT_H
#define STANDARDANN_INT8_SHIFT_WEIGHTS_8BIT_H

#include <stdint.h>

/* Network Configuration */
#define STANDARDANN_INT8_SHIFT_INPUT_SIZE  36
#define STANDARDANN_INT8_SHIFT_HIDDEN_SIZE 14
#define STANDARDANN_INT8_SHIFT_OUTPUT_SIZE 10
#define STANDARDANN_INT8_SHIFT_BITS        8

/* Shift amounts for integer-only inference (scale = 2^shift) */
/* Use these for requantization: out = (acc + (1 << (shift-1))) >> shift */
#define STANDARDANN_INT8_SHIFT_INPUT_SHIFT (0)
#define STANDARDANN_INT8_SHIFT_FC1_WEIGHT_SHIFT (-8)
#define STANDARDANN_INT8_SHIFT_FC1_BIAS_SHIFT (-9)
#define STANDARDANN_INT8_SHIFT_FC1_OUTPUT_SHIFT (1)
#define STANDARDANN_INT8_SHIFT_FC2_WEIGHT_SHIFT (-8)
#define STANDARDANN_INT8_SHIFT_FC2_BIAS_SHIFT (-6)
#define STANDARDANN_INT8_SHIFT_FC2_OUTPUT_SHIFT (-1)

/* Pre-computed shift amounts for integer-only inference */
/* Convention: positive = left shift, negative = right shift */
/* Use shift_round() helper: if shift >= 0: x << shift, else: (x + (1 << (-shift-1))) >> (-shift) */
#define STANDARDANN_INT8_SHIFT_FC1_REQUANT_SHIFT (-9)  /* acc_shift - out_shift */
#define STANDARDANN_INT8_SHIFT_FC1_BIAS_ALIGN_SHIFT (-1)  /* bias_shift - acc_shift */
#define STANDARDANN_INT8_SHIFT_FC2_REQUANT_SHIFT (-6)  /* acc_shift - out_shift */
#define STANDARDANN_INT8_SHIFT_FC2_BIAS_ALIGN_SHIFT (1)  /* bias_shift - acc_shift */

/*
 * OPTIONAL: Scale factors for debugging/verification.
 * These are NOT needed for integer inference - just do int math directly.
 * Define STANDARDANN_INT8_SHIFT_INCLUDE_SCALES to include them.
 */
#ifdef STANDARDANN_INT8_SHIFT_INCLUDE_SCALES

/* Weight Scale Factors (real_value = int_value * scale) */
#define STANDARDANN_INT8_SHIFT_FC1_WEIGHT_SCALE 0.0039062500f
#define STANDARDANN_INT8_SHIFT_FC1_BIAS_SCALE 0.0019531250f
#define STANDARDANN_INT8_SHIFT_FC2_WEIGHT_SCALE 0.0039062500f
#define STANDARDANN_INT8_SHIFT_FC2_BIAS_SCALE 0.0156250000f

#endif /* STANDARDANN_INT8_SHIFT_INCLUDE_SCALES */

/* fc2_weight: shape=[10, 14], total=140 */
static const int8_t StandardANN_Int8_Shift_fc2_weight[140] = {
      52,   -8,  -26,   30,  -21,   40,   36,  -27,   31,    1,    2,  -17,    9,  -33,   -9,   -9,
      39,  -16,  -24,    1,  -46,   71,  -59,  -18,  -19,  -37,   55,    7,   40,   53,   49,  -24,
     -32,   30,  -19,    5,   12,   -5,   -3,   18,   36,   68,   47,   60,   23,  -38,  -32,  -44,
     -49,  -38,  -25,  -32,   33,    9,  -29,   26,   57,    7,  -16,   33,  -54,  -29,   32,  -12,
       4,  -39,  -20,   66,  -48,   -1,    4,   21,   18,   51,  -60,   -1,  -37,  -22,  -20,  -14,
      47,   18,  -33,   36,  -65,  -70,   -8,  -41,  -42,  -14,   42,   26,   69,  -24,  -50,  -15,
      15,    2,    9,   39,   -8,   72,   -1,   -7,  -47,  -11,    1,   17,  -41,   28,  -58,   20,
     -45,    0,   28,   53,  -21,  -29,  -45,   -6,  -26,  -55,   47,   10,   55,   43,  -67,    2,
      11,  -28,  -14,  -34,   44,  -43,  -10,  -42,    2,   39,  -19,  -39,
};

/* fc2_bias: shape=[10], total=10 */
static const int8_t StandardANN_Int8_Shift_fc2_bias[10] = {
     -32,   62,  -78,   60,  -37,   25,   -9,   -9,  -52,   46,
};

#endif /* STANDARDANN_INT8_SHIFT_WEIGHTS_8BIT_H */