/*
 * StandardANN_Int8_Shift - 8-bit Quantized Weights for Embedded Deployment
 * Generated by gilgamesh snntorch_comparison.py
 *
 * Network: 36 -> 14 -> 10
 * Quantization: 8-bit signed integers (-128 to 127)
 * Format: real_value = int_value * scale
 */

#ifndef STANDARDANN_INT8_SHIFT_WEIGHTS_8BIT_H
#define STANDARDANN_INT8_SHIFT_WEIGHTS_8BIT_H

#include <stdint.h>

/* Network Configuration */
#define STANDARDANN_INT8_SHIFT_INPUT_SIZE  36
#define STANDARDANN_INT8_SHIFT_HIDDEN_SIZE 14
#define STANDARDANN_INT8_SHIFT_OUTPUT_SIZE 10
#define STANDARDANN_INT8_SHIFT_BITS        8

/* Shift amounts for integer-only inference (scale = 2^shift) */
/* Use these for requantization: out = (acc + (1 << (shift-1))) >> shift */
#define STANDARDANN_INT8_SHIFT_INPUT_SHIFT (0)
#define STANDARDANN_INT8_SHIFT_FC1_WEIGHT_SHIFT (-8)
#define STANDARDANN_INT8_SHIFT_FC1_BIAS_SHIFT (-9)
#define STANDARDANN_INT8_SHIFT_FC1_OUTPUT_SHIFT (1)
#define STANDARDANN_INT8_SHIFT_FC2_WEIGHT_SHIFT (-8)
#define STANDARDANN_INT8_SHIFT_FC2_BIAS_SHIFT (-6)
#define STANDARDANN_INT8_SHIFT_FC2_OUTPUT_SHIFT (-1)

/* Pre-computed shift amounts for integer-only inference */
/* Convention: positive = left shift, negative = right shift */
/* Use shift_round() helper: if shift >= 0: x << shift, else: (x + (1 << (-shift-1))) >> (-shift) */
#define STANDARDANN_INT8_SHIFT_FC1_REQUANT_SHIFT (-9)  /* acc_shift - out_shift */
#define STANDARDANN_INT8_SHIFT_FC1_BIAS_ALIGN_SHIFT (-1)  /* bias_shift - acc_shift */
#define STANDARDANN_INT8_SHIFT_FC2_REQUANT_SHIFT (-6)  /* acc_shift - out_shift */
#define STANDARDANN_INT8_SHIFT_FC2_BIAS_ALIGN_SHIFT (1)  /* bias_shift - acc_shift */

/*
 * OPTIONAL: Scale factors for debugging/verification.
 * These are NOT needed for integer inference - just do int math directly.
 * Define STANDARDANN_INT8_SHIFT_INCLUDE_SCALES to include them.
 */
#ifdef STANDARDANN_INT8_SHIFT_INCLUDE_SCALES

/* Weight Scale Factors (real_value = int_value * scale) */
#define STANDARDANN_INT8_SHIFT_FC1_WEIGHT_SCALE 0.0039062500f
#define STANDARDANN_INT8_SHIFT_FC1_BIAS_SCALE 0.0019531250f
#define STANDARDANN_INT8_SHIFT_FC2_WEIGHT_SCALE 0.0039062500f
#define STANDARDANN_INT8_SHIFT_FC2_BIAS_SCALE 0.0156250000f

#endif /* STANDARDANN_INT8_SHIFT_INCLUDE_SCALES */

/* fc1_weight: shape=[14, 36], total=504 */
static const int8_t StandardANN_Int8_Shift_fc1_weight[504] = {
      33,   35,  -10,   39,   -9,    9,  -21,   25,   38,  -31,   37,    8,   32,    6,   21,   -6,
      33,    6,  -20,   11,  -20,   -5,  -17,   28,  -34,  -20,  -12,  -26,    4,  -42,   39,  -36,
      33,    7,  -14,   26,  -10,   19,   13,  -11,  -26,  -34,    8,   49,   36,   31,   15,  -24,
       1,  -83,  -66,   13,  -19,    1,    8,   -2,    4,    2,   23,  -19,   18,   36,  -12,   11,
      26,    8,   24,  -12,   -1,  -39,   12,   -1,   56,  -20,  -26,  -17,  -14,   32,   30,   47,
      -8,   -7,   38,   -2,   39,  -13,   13,  -16,  -29,   26,   23,  -13,   34,   10,  -35,  -10,
      54,    6,    4,  -38,   -9,   26,    9,  -16,   14,  -15,  -21,   -9,  -20,  -11,   54,   18,
      30,  -22,  -11,    3,   18,  -29,    5,   -5,   18,    5,   18,  -26,   -7,   -5,    3,  -13,
      32,  -15,   47,   30,  -20,   46,   -4,   -8,  -24,  -26,   29,    9,   38,  -14,   49,  -14,
     -15,   -2,   -3,   -6,    9,  -43,   13,   -9,   49,   67,   -2,  -41,   30,   17,  -53,    7,
      87,    1,    3,  -21,    9,   11,   -9,   22,    3,   -6,   -4,  -45,  -33,  -27,  -33,   -9,
      18,   49,   24,  -48,   13,   25,   11,  -12,   26,   26,   19,   -4,   -8,    8,   -4,   -9,
      31,   33,   -1,   -6,    4,    1,   13,   15,  -36,  -13,   33,   20,    1,  -22,  -23,  -35,
     -11,   18,   30,   23,  -34,  -22,   -3,   45,   18,    1,   30,   -5,  -16,   43,   -8,    4,
     -29,   38,   42,   27,  -18,  -30,  -24,   26,   30,   47,   34,   21,    7,  -23,  -25,  -28,
      29,  -11,   -1,  -12,    4,  -18,  -16,   26,   -1,   39,   -2,  -20,   -2,  -17,   -4,    5,
      36,  -22,   21,  -10,   11,  -21,    4,  -14,   15,    7,  -39,  -21,  -12,   -5,   26,  -56,
      61,    5,  -34,   26,  -28,   30,   37,   16,   35,   -7,    2,  -26,  -39,   -8,  -38,   40,
      29,  -12,  -12,  -15,  -15,  -41,    6,  -37,   -2,   19,    1,  -31,  -11,  -21,  -21,  -83,
      23,   33,  -25,   49,   52,   -9,   54,    6,  -39,   19,   51,   37,   21,   18,  -13,   -1,
     -36,  -21,   15,   13,  -12,  -25,  -29,  -42,  -23,    5,   38,   -8,   -1,    5,   36,  -11,
       0,   31,   28,  -38,   16,    8,   -6,   -1,  -74,  -45,  -19,  -22,  -14,   14,   28,   15,
       7,   28,  -29,   -1,   28,   24,   -7,   55,  -36,  -40,  -23,    3,  -22,  -16,  -10,  -28,
      18,   22,   24,   28,  -37,    9,    0,  -52,   16,   39,   23,  -26,   38,  -22,    8,   19,
     -20,   64,   17,   19,   49,  -13,  -29,  -49,   27,   17,   12,  -40,  -27,    2,  -11,  -14,
      10,   38,    5,  -24,    0,   -6,   27,  -26,  -25,   53,    8,  -44,   49,  -19,   25,   19,
      28,   64,  -10,  -23,   -7,  -53,  -20,  -39,  -15,    4,   -1,  -27,   13,   15,   19,    0,
      -7,   33,  -25,   36,   -7,   10,    1,   14,   -6,   35,    7,   43,   51,  -10,  -23,   25,
      40,  -23,    6,  -32,  -25,   15,   18,   18,   -3,   46,   12,  -19,    6,   20,   24,  -21,
      25,  -12,  -26,  -14,   41,   36,   38,   25,   32,   -6,  -23,   21,  -22,  -29,  -14,    9,
      22,  -17,  -25,    6,  -25,  -28,   22,   -7,   39,   42,   13,   15,   10,    1,   -3,    1,
      16,   40,  -11,  -18,  -10,  -21,    7,   32,
};

/* fc1_bias: shape=[14], total=14 */
static const int8_t StandardANN_Int8_Shift_fc1_bias[14] = {
      67,   73,  -92,  -80,   -2,  -22,  -16,  -91,   38,  -96,  -15,  -87,   55,  -81,
};

/* fc2_weight: shape=[10, 14], total=140 */
static const int8_t StandardANN_Int8_Shift_fc2_weight[140] = {
      52,   -8,  -26,   30,  -21,   40,   36,  -27,   31,    1,    2,  -17,    9,  -33,   -9,   -9,
      39,  -16,  -24,    1,  -46,   71,  -59,  -18,  -19,  -37,   55,    7,   40,   53,   49,  -24,
     -32,   30,  -19,    5,   12,   -5,   -3,   18,   36,   68,   47,   60,   23,  -38,  -32,  -44,
     -49,  -38,  -25,  -32,   33,    9,  -29,   26,   57,    7,  -16,   33,  -54,  -29,   32,  -12,
       4,  -39,  -20,   66,  -48,   -1,    4,   21,   18,   51,  -60,   -1,  -37,  -22,  -20,  -14,
      47,   18,  -33,   36,  -65,  -70,   -8,  -41,  -42,  -14,   42,   26,   69,  -24,  -50,  -15,
      15,    2,    9,   39,   -8,   72,   -1,   -7,  -47,  -11,    1,   17,  -41,   28,  -58,   20,
     -45,    0,   28,   53,  -21,  -29,  -45,   -6,  -26,  -55,   47,   10,   55,   43,  -67,    2,
      11,  -28,  -14,  -34,   44,  -43,  -10,  -42,    2,   39,  -19,  -39,
};

/* fc2_bias: shape=[10], total=10 */
static const int8_t StandardANN_Int8_Shift_fc2_bias[10] = {
     -32,   62,  -78,   60,  -37,   25,   -9,   -9,  -52,   46,
};

#endif /* STANDARDANN_INT8_SHIFT_WEIGHTS_8BIT_H */